version: "3.8"

services:
  zeppelin:
    image: apache/zeppelin:0.10.0
    container_name: zeppelin
    ports:
      - "8080:8080"
    environment:
      ZEPPELIN_NOTEBOOK_DIR: /zeppelin/notebook
      ZEPPELIN_LOG_DIR: /zeppelin/logs
      ZEPPELIN_RUN_MODE: docker
      ZEPPELIN_CREDENTIALS_PERSIST: "true"
      ZEPPELIN_CREDENTIALS_ENCRYPT_KEY: your_secure_aes_key_here
      ZEPPELIN_SERVER_ADDR: "0.0.0.0"
      ZEPPELIN_NOTEBOOK_STORAGE: org.apache.zeppelin.notebook.repo.VFSNotebookRepo
    volumes:
      - ./notebook:/zeppelin/notebook
      - ./logs:/zeppelin/logs
    restart: unless-stopped
